"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { createClient } from "../../../lib/supabase/client";

type App={id:string;status:string;mission_id:string;missions:{city:string;starts_at:string;ends_at:string;candidate_rate:number;tariff_grid:{job:string}|null}|null};
type Hours={mission_id:string;hours:number;validated_at:string|null};
type Detail={mission_id:string;job:string;city:string;starts_at:string;ends_at:string;candidate_rate:number;employer_ttc:number;establishment_name:string|null;address:string|null;establishment_phone:string|null};

export default function MesMissions(){
 const [apps,setApps]=useState<App[]>([]);const [worked,setWorked]=useState<Hours[]>([]);const [details,setDetails]=useState<Record<string,Detail>>({});const [message,setMessage]=useState("Chargement…");
 useEffect(()=>{(async()=>{const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user){location.href="/connexion";return;}const a=await s.from("applications").select("id,status,mission_id,missions(city,starts_at,ends_at,candidate_rate,tariff_grid(job))").eq("extra_id",user.id).order("created_at",{ascending:false});const h=await s.from("worked_hours").select("mission_id,hours,validated_at").eq("extra_id",user.id);if(a.error||h.error){setMessage("Impossible de charger vos missions.");return;}setApps((a.data||[]) as unknown as App[]);setWorked((h.data||[]) as Hours[]);const accepted=(a.data||[]).filter((x:any)=>x.status==="accepted");const loaded:Record<string,Detail>={};for(const x of accepted){const d=await s.rpc("get_my_mission_details",{p_mission_id:x.mission_id});if(d.data?.[0])loaded[x.mission_id]=d.data[0] as Detail;}setDetails(loaded);setMessage("");})()},[]);
 return <main className="appShell"><header className="appHeader"><Link className="brand" href="/">FOOD<span>FORCE</span></Link><div className="appName">EXTRAS</div><nav><Link href="/extras">Missions</Link><Link href="/extras/mes-missions">Mes missions</Link><Link href="/extras/profil">Profil</Link></nav></header><section className="pageIntro"><span className="eyebrow">FOODFORCE EXTRAS</span><h1>Mes missions</h1><p>Avant sélection, l'établissement reste anonyme. Après acceptation, les informations nécessaires apparaissent ici.</p></section><section className="missionGrid">{apps.map(a=>{const h=worked.find(x=>x.mission_id===a.mission_id);const d=details[a.mission_id];return <article className="missionCard" key={a.id}><div className="missionTop"><span className={a.status==="accepted"?"tag acceptedTag":"tag"}>{a.status}</span></div><h3>{a.missions?.tariff_grid?.job||"Mission"}</h3><p className="missionTime">{a.missions?.city} · {a.missions?.starts_at?new Date(a.missions.starts_at).toLocaleString("fr-FR"):""}</p>{d?<div className="revealed"><b>✓ Mission confirmée</b><strong>{d.establishment_name||"Établissement partenaire"}</strong><span>📍 {d.address||d.city}</span>{d.establishment_phone&&<span>📞 {d.establishment_phone}</span>}</div>:<div className="anonymous"><span>🏨</span><div><b>Établissement anonymisé</b><small>Les coordonnées seront révélées si votre candidature est acceptée.</small></div></div>}<strong className="rate">{Number(a.missions?.candidate_rate||0).toFixed(2)} <small>MAD/h</small></strong>{h&&<small>{h.hours} h validées {h.validated_at?"✅":"⏳"}</small>}</article>})}</section>{message&&<p className="statusMessage">{message}</p>}</main>}